FROM ubuntu:latest
RUN apt-get update && apt-get install python3-pip -y && pip3 install requests 
RUN apt-get clean \ && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp*
WORKDIR /authent/data/
ADD authentication.py /authent/authentication.py
WORKDIR /authent/ 
CMD sleep 10; python3 authentication.py
