FROM ubuntu:latest
RUN apt-get update && apt-get install python3-pip -y && pip3 install requests 
RUN apt-get clean \ && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp*
WORKDIR /authoriz/data/
ADD authorization.py /authoriz/authorization.py
WORKDIR /authoriz/
CMD sleep 10; python3 authorization.py

